// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_-oJILg3hIJhsRRbbfb9JP-wSvdrjkyA',
    appId: '1:766918308869:web:2eaf7ec087c263d57d986c',
    messagingSenderId: '766918308869',
    projectId: 'attendid-61680',
    authDomain: 'attendid-61680.firebaseapp.com',
    storageBucket: 'attendid-61680.firebasestorage.app',
    measurementId: 'G-RRKY2FHTFV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0oMbqBgWFqtLKzvkM-URZ10Zm3--GcTk',
    appId: '1:766918308869:android:7d7284c0640fbf7c7d986c',
    messagingSenderId: '766918308869',
    projectId: 'attendid-61680',
    storageBucket: 'attendid-61680.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCa9fewA_1ofQbAuHl2YXYgeBuUf4x7bo',
    appId: '1:766918308869:ios:b4c5d341c1f5ea237d986c',
    messagingSenderId: '766918308869',
    projectId: 'attendid-61680',
    storageBucket: 'attendid-61680.firebasestorage.app',
    androidClientId: '766918308869-68fn4vohgel82k0qc26ddavg1q5bn7av.apps.googleusercontent.com',
    iosClientId: '766918308869-98ddlb36ibrveah7ts49600fj3vibh35.apps.googleusercontent.com',
    iosBundleId: 'com.example.attendidClean',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCa9fewA_1ofQbAuHl2YXYgeBuUf4x7bo',
    appId: '1:766918308869:ios:b4c5d341c1f5ea237d986c',
    messagingSenderId: '766918308869',
    projectId: 'attendid-61680',
    storageBucket: 'attendid-61680.firebasestorage.app',
    androidClientId: '766918308869-68fn4vohgel82k0qc26ddavg1q5bn7av.apps.googleusercontent.com',
    iosClientId: '766918308869-98ddlb36ibrveah7ts49600fj3vibh35.apps.googleusercontent.com',
    iosBundleId: 'com.example.attendidClean',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_-oJILg3hIJhsRRbbfb9JP-wSvdrjkyA',
    appId: '1:766918308869:web:47234af824cbac8f7d986c',
    messagingSenderId: '766918308869',
    projectId: 'attendid-61680',
    authDomain: 'attendid-61680.firebaseapp.com',
    storageBucket: 'attendid-61680.firebasestorage.app',
    measurementId: 'G-GN8H3DKE9G',
  );
}
